### ISSUE TITLE
Organize queries into a tree-like sturcture for easier navigation

### ISSUE THREAD

**Issue by eeriksp** [chrisclark/django-sql-explorer#518]
In the project where we are using Django SQL explorer the number of queries has grown so large that it is hard to navigate.

I would propose to add a field `path` to the query which would function like a regular filesystem path. Based on that path queries could be displayed in the list view as a tree-like structure. For example queries with names A, B, C, D and paths `/research/europe/`, `/research/europe/`, `/research/usa`, and `sales`, respectively, could be shown as

* `research`
  * `europe`
    * A
    * B
  * `usa`
    * C 
* `sales`
  * D

This change would be **backwards compatible** as the `path` variable would not be required and the path could default to the root directory or some special "uncategorized" category.

Also, this would open up the possibility to use that path for access management in the future such as giving a user read or write access to all queries under a specific path. However, that is just a though and not directly linked to the current proposal.

If that idea sounds interesting, **I would be happy to prepare a PR**.

**Comment by marksweb** [comment]
Have you seen that it can group queries with the same prefix?

**Comment by eeriksp** [comment]
> Have you seen that it can group queries with the same prefix?

Where is this documented? I could not find that.

**Comment by marksweb** [comment]
@eeriksp it might not be. I think I discovered it by chance
