### ISSUE TITLE
django Data explorer

### ISSUE THREAD

**Issue by stanelyg** [chrisclark/django-sql-explorer#546]
django Data explorer can't display schemas when the database is mysql  any assistance I will be grateful

**Comment by marksweb** [comment]
Can you be more specific about what you're seeing?

I don't have a mysql project that I can run this on at the moment.

**Comment by ernstki** [comment]
@stanelyg A screenshot would help, if you're still seeing this.

We are using the extension with a MySQL database, no problems with displaying the schemata, so it's not broken for everyone, if that's any consolation.
