### ISSUE TITLE
Download button stopped working

### ISSUE THREAD

**Issue by jefer94** [chrisclark/django-sql-explorer#588]
We recently switch to Django 5, when I pressed Download button in any side, it shows me `Query saved`, apparently this button is doing the function of `Save only` button.

**Comment by chrisclark** [comment]
investigating...

**Comment by chrisclark** [comment]
What version of SQL Explorer are you running? Can you try with the latest version (4.0.2)?

I am running it locally and see this UI, which works fine when (for example) I click "CSV".

<img width="505" alt="image" src="https://github.com/chrisclark/django-sql-explorer/assets/693700/03066e1f-9aef-464e-b2d3-ed242606be6f">

**Comment by jefer94** [comment]
I saw yesterday that the issue is related to CORS, thinking in it, a part of the problem is solved doing this

gcloud.json
```json
[
    {
        "origin": [
            "https://x.com/*"
        ],
        "method": ["GET", "PUT", "POST", "DELETE", "HEAD"],
        "headers": ["x-custom-header"],
        "maxAgeSeconds": 3600
    }
]
```

```bash
gsutil cors get gcloud.json gs://xyz
```

Many issues were resolved with it, but, technically this should be considered an issue with CORS, but it worked with Django admin, so, I think that is not so accurate, I saw you used a custom Django tag instead of the regular STATIC directive, maybe it should cause the difference, I'm using `django-storages` with Google Cloud Storage.

Also, I saw this warning
- Firefox
```txt
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html for further details and to join the discussion on related tools and features!
```
- Chrome
```txt
A preload for 'https://storage.googleapis.com/breathecode_staticfiles/explorer/bootstrap-icons.woff2?7141511ac37f13e1a387fb9fc6646256' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.
56/:1 The resource https://storage.googleapis.com/breathecode_staticfiles/explorer/bootstrap-icons.woff2?7141511ac37f13e1a387fb9fc6646256 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

It worked locally, but it is using `whitenoise` instead of `django-storages`, yesterday when I pressed the download button I saw a CORS error (after run this command) maybe due to the cache, this should be an issue of `django-storages` because it should set those settings automatically, but just fail with `django-sql-explorer`.

I can download the CSV within this URL `/explorer` but not `/explorer/56`.

**Comment by chrisclark** [comment]
@jefer94 I'd love to fix this, but I'm not sure how. Is there anything you think I could do within the app itself that would make this work better? It seems like the CORS issue is related to the GCS configuration, and not SQL Explorer.

**Comment by gabriels1234** [comment]
@chrisclark as a workaround, I added a Middleware to my app that replaces the static path for the django-storages prefixed version. 
I don't know how to better tackle this as a PR (fixing vite_asset or replacing it by "static" simple_tag) , but I'd gladly welcome any pointer and I'm happy to contribute.

**Comment by gabriels1234** [comment]
Finally, I was able to fix it by setting STATIC_URL to have the s3 bucket url + '/static/'.

**Comment by chrisclark** [comment]
@gabriels1234 thanks! Is your conclusion that SQL Explorer should be doing something different, or that you had an incorrect STATIC_URL setting?

**Comment by gabriels1234** [comment]
@chrisclark the problem comes because it's not REQUIRED for django to have STATIC_URL defined differently when using django-storages (s3 at least). At the same time, setting the value does not hurt, so leaving this comment should be helpful for others to move forward.

Thanks for you attention!
