### ISSUE TITLE
Make library compatible with CSP script-src (unsafe-inline)

### ISSUE THREAD

**Issue by abedimhosein** [chrisclark/django-sql-explorer#591]
Because of this type of tag:
`<script type="text/javascript">
        // something
</script>`

inside the html files, some pages(like playground or play.html) on sites that have set CSP _script-src 'self'_ to their response headers do not work at all!

[Content-Security-Policy Header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src)

I use [django-csp](https://github.com/mozilla/django-csp) library to set CSP Header and this library suggests to use CSP_NONCE tag to use inline js inside html file like this:

![image](https://github.com/chrisclark/django-sql-explorer/assets/56556325/8cd9d944-05a3-43bd-a09d-38042b31fc79)

**Comment by chrisclark** [comment]
I proposed a fix here. Please take a look and leave any comments and I can merge and release as a patch.

https://github.com/chrisclark/django-sql-explorer/pull/594

**Comment by abedimhosein** [comment]
I looked into this, I think it's ok and it solves the problem, thanks.

**Comment by chrisclark** [comment]
Merged. Closing the issue. Thanks for finding it! The project is better for it.
