### ISSUE TITLE
Custom User Model with no email field

### ISSUE THREAD

**Issue by abedimhosein** [chrisclark/django-sql-explorer#592]
If `settings.AUTH_USER_MODEL` is a custom user model that does not have an email field, the `created_by_user_email` function throws an AttributeError exception.

**Comment by marksweb** [comment]
This has been raised before in #551 and at the time I felt like there were further problems if a user doesn't have an email address.

**Comment by chrisclark** [comment]
Addressed via https://github.com/chrisclark/django-sql-explorer/pull/606
