### ISSUE TITLE
Getting blocked by CORS policy for static files

### ISSUE THREAD

**Issue by SanjayPatel39** [chrisclark/django-sql-explorer#608]
My application's Static files are in AWS S3.
When using `explorer/play/` getting `blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.` in browser console.

Already tried Django config for CORS policy.

```
CORS_ORIGIN_ALLOW_ALL = True
.
.
.
INSTALLED_APPS = [
   .,
   .,
   .,
    'corsheaders',
    'explorer',
    .,
   .,
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    .,
    .,
]

```

My Application is working fine with Old version of 
django-sql-explorer==2.0
Django==3.2.4

but not working in 
Django==5.0.2
django-sql-explorer==4.0.1

**Comment by marksweb** [comment]
Sounds like it might be worth looking on S3 at the bucket settings and doing some searching for articles on bucket CORS configs like this;

https://blog.mikaeels.com/how-to-configure-cors-for-an-aws-s3-bucket

**Comment by SanjayPatel39** [comment]
Thanks It fixed the issue.
