### ISSUE TITLE
What is latest version?

### ISSUE THREAD

**Issue by tresero** [chrisclark/django-sql-explorer#622]
I am not sure why, but I'm showing 4.2, but github is at 4.0

django-sql-explorer==4.2

This is a fresh install of django. Plus my UI is totally different.

**Comment by marksweb** [comment]
It's 4.2. And the UI has changed a lot recently. I think 4.0 was the frontend overhaul.

Repo tags are 4.2, https://github.com/chrisclark/django-sql-explorer/tags
Repo releases is 4.2, https://github.com/chrisclark/django-sql-explorer/releases
Pypi is 4.2, https://pypi.org/project/django-sql-explorer/

**Comment by tresero** [comment]
Thanks, not sure why my earlier app worked from admin, but it works now. Thanks!
