### ISSUE TITLE
UI Wonky

### ISSUE THREAD

**Issue by tresero** [chrisclark/django-sql-explorer#628]
I'm not sure why, but I can't get any sort, or show schema or anything to work. I'm running 4.3. Any guidance? This was updated from 3.x but it's not a full time project, so I don't work on it daily. 

![image](https://github.com/chrisclark/django-sql-explorer/assets/1476286/7c76ccf7-ae0b-472f-9ebb-97c72c4f0888)

You can see there are just empty boxes and when I click show schema it does nothing?

Thanks

**Comment by chrisclark** [comment]
Can you please share any errors that might be showing up in the browser console?

**Comment by tresero** [comment]
Not sure this helps. I'm a database person, not a JS dev, but I think it's some kind of permissions error. This is on my home network.

![image](https://github.com/chrisclark/django-sql-explorer/assets/1476286/70f68374-cf5a-41c9-9593-8930c2b1d123)

**Comment by tresero** [comment]
Okay, I fixed it. Sorry for the issue. Didn't realize that I needed to add the dev machine to CORS. deleted the image for security reasons.

**Comment by chrisclark** [comment]
Ah -- if you are going to use S3 to host your Django static assets, you need to allow those assets to be accessed by your site. This will happen with any and all Django assets that your site tries to load. You need to add a CORS policy to the s3 bucket:

https://docs.aws.amazon.com/AmazonS3/latest/userguide/enabling-cors-examples.html
